### ISSUE TITLE
Local server doesn't start again on Windows

### ISSUE THREAD

**Issue by Boso101** [hiddenswitch/Spellsource-Server#10]
Hey, when I attempt to start a server I get stuck on 93% with this 

![image](https://user-images.githubusercontent.com/22697660/33794357-b1d3cec0-dd1a-11e7-84e5-23f1f9d6d09f.png)

**Comment by doctorpangloss** [comment]
I appreciate the kind directory name...

It looks like the mongo embedder has an issue on Windows. I'll test it shortly and try to run down what the problem is. In the meantime, try to do:

rmdir /s "C:\Users\Boso\Documents\Spellsource Hearthstone best project ever\Spellsource-Server-master\net\.mongo"

**Comment by doctorpangloss** [comment]
I could reproduce this exception by running `./gradlew net:local` twice. Take care to completely close all your running servers / only run one server at a time. Otherwise it will definitely glitch out!

**Comment by Boso101** [comment]
is there a command to make sure the server stops? I have had a look in task manager doesnt seem to be any instances of it running

**Comment by doctorpangloss** [comment]
This is an excellent question for Windows. On Mac, I hit Ctrl+C and the server has been killed.

Deleting the `.mongo` directory with `rmdir /s "C:\Users\Boso\Documents\Spellsource Hearthstone best project ever\Spellsource-Server-master\net\.mongo"` should work, but I'm afraid that will be a big hassle.

I will grab a Windows machine tomorrow to reproduce the issue.

**Comment by Boso101** [comment]
![image](https://user-images.githubusercontent.com/22697660/33794951-a781aa36-dd25-11e7-8a18-e42640493163.png)
Yep, rebooted my computer and same problem

**Comment by doctorpangloss** [comment]
Try pulling the latest now. I got this to reproduce another way.

**Comment by Boso101** [comment]
Still seems to hang on 93% It has been 7minutes I will wait a bit longer just incase

**Comment by doctorpangloss** [comment]
Yeah there's something very glitchy with the embedded `mongod`... Working on it.

**Comment by Boso101** [comment]
No worries, its to be expected with a project like this

**Comment by doctorpangloss** [comment]
@Boso101 some progress has been made by using a virtual machine, though it's quite slow. Unfortunately Windows will always shock you with how utterly unsuitable it is for modern networking applications programming.

**Comment by doctorpangloss** [comment]
Fix is deployed in the latest client and server, please follow the directions in the README.md
