### ISSUE TITLE
Roll still does not retain any changes to stats or effects.

### ISSUE THREAD

**Issue by LyokoBarbossa** [hiddenswitch/Spellsource-Server#1013]
Reproduction steps:

    1. Play a minion with a buff to stats or added attribute.
    2. Play Roll on said minion.
    3. Buffs vanish from minion both in hand and when played. Roll should allow buffs to remain.

Platform: [ X ] Windows, [ ] Mac

**Comment by doctorpangloss** [comment]
Not yet architecturally possible with Spellsource but this will be revisited in the future. At the moment the attack and hp bonuses are retained.
