### ISSUE TITLE
Multiple Problems with Lady Delilah

### ISSUE THREAD

**Issue by Rumu11** [hiddenswitch/Spellsource-Server#1015]
Lady Delilah from Verdant dreams has a few issues:

It should be VIOLET instead of ANY.
It gains +2/+0 instead of the intended +1/+1 per lifesteal card played.
Its aura does not update/apply in hand, causing it to be less intuitive and not work as intended with cards such as Felfire Drake.

**Comment by doctorpangloss** [comment]
> Its aura does not update/apply in hand, causing it to be less intuitive and not work as intended with cards such as Felfire Drake.

This will get its own issue
