### ISSUE TITLE
Screen is dimmed and End Turn and accept mulligan button unable to be used in 1v1 challenges 

### ISSUE THREAD

**Issue by Pircival** [hiddenswitch/Spellsource-Server#1032]
Platform: [X] Web, [ ] Mac

When I try to click them, nothing happens. Same with eye icon

Design or Graphics Glitches:
![image](https://user-images.githubusercontent.com/37511858/54098657-75f0c180-4383-11e9-9571-763c941710d7.png)

**Comment by doctorpangloss** [comment]
This seems like a pretty serious bug I'm taking a look at it now

**Comment by doombubbles** [comment]
Old Client
