### ISSUE TITLE
Exhausted Minions unfreeze at end of turn

### ISSUE THREAD

**Issue by Rumu11** [hiddenswitch/Spellsource-Server#1040]
Play a minion, or summon a token (without charge and maybe rush).
Freeze it.
End your turn.
Watch it unfreeze, even though it was unable to make an attack.

Minions should only unfreeze if they were otherwise able to make an attack, but didn't. (Unsure about how it works with rush.)

**Comment by doombubbles** [comment]
Now that Freezing is instead Stunning, it's no longer clear whether we should care about the old Hearthstone rules.
