### ISSUE TITLE
ChooseAndReshuffleSpell doesn't reshuffle, though you can choose

### ISSUE THREAD

**Issue by RicochetBeret** [hiddenswitch/Spellsource-Server#1068]
Just what it sounds like. Hero Power. Upgraded Hero Power. Passive triggers. Battlecries. No instance of ChooseAndReshuffleSpell actually gets rid of the cards that you choose. I believe the problem is with the spell class itself, as i can't find a way the timeweaver cards' json programming is flawed. If i need to do something to fix the json, let me know.

**Comment by doctorpangloss** [comment]
jaw drops. yeah i'll fix it, i must have bungled the test

**Comment by doctorpangloss** [comment]
yes, i see that i accidentally implemented it as shuffling a copy, based on an old misunderstanding. easy fix
