### ISSUE TITLE
Invoke should be reworked to incorporate choice cards

### ISSUE THREAD

**Issue by TheFlawlessWalrus** [hiddenswitch/Spellsource-Server#1083]
Invoke has been redesigned to utilise choice cards, akin to ones from Choose One cards, Adapt cards and Kalimos etc. The step by step should go something like this:

1. Invoke card glows yellow (or another colour) when the player has enough mana to afford the invoke cost.
2. If the player had enough mana to afford the/an invoke cost, they're given two choice cards, each stating the cards effect and displaying their respective mana cost.
3. The first card will naturally display the cards default cost but the cards cost will only be overriden if an Invoke cost is paid, meaning cost modifiers from other sources will still apply but only to the first choice.
4. If any Invoke costs are added to the card from other sources, such as Mad Prophet Rosea, or a soon to come out card called Recycle Rabbit, those choices will show up as third or fourth choice cards among the others.
5. The player chooses one of the choice cards and then pays for the card, spending the mana for the choice they picked. If the final cost of the card was enough to activate any Invoke effects that weren't picked and an Invoke choice was made, those Invoke effects still apply.
Example ~ You play Mad Prophet Rosea and then a spell with Invoke on it naturally such as Potion of Creation. The choices of summoning a 3-Cost minion for 2, an 8-Cost minion instead for 7 and The Devourer also for 10 show up. If the first choice is picked, a 3 drop is summoned. If the second choice is picked, an 8 drop is summoned. If the third choice is picked, an 8 drop AND The Devourer are summoned.

https://imgur.com/XEJXSdH
When first implementing the change just give all the invocation choices placeholder names, I'll work finalising everything afterwards.

**Comment by doombubbles** [comment]
I looked into this and actually basically got it work in the back end before I found out the new client doesn't actually still work with the old choose one system lol.

For now I think this sadly won't be a thing
