### ISSUE TITLE
Pre-buff ordering change (Maybe ordering change in general)

### ISSUE THREAD

**Issue by TheFlawlessWalrus** [hiddenswitch/Spellsource-Server#1097]
Many Summoner cards and a number of cards from other classes dotted about have pre-buffs, which are buffs that trigger on the next minion or next minions summoned that turn (next played, in Barons case). This includes cards like Dramatic Entrance, Wild Mutation and Lackey Break.

As it currently stands, it only actually applies the buff after the minion is summoned, meaning the battlecry effect of any minion coming out will trigger before the minion is summoned, then after that all resolves the minion is summoned to the board, and then that minion gets buffed.

If that minion's battlecry summons another minion, such as a Razorfen Hunter summoning its Boar or a Bromeliad Pup summoning its other Bromeliad, the token gets summoned first and gets the buff instead.

I think the way this works isn't intuitive, which wouldn't be that much of an issue in normal Hearthstone due to it being very edge-case and rarely relevent, due to stuff like pre-buffs not existing, and the ordering only ever being noticable with cards like Addled Grizzly and Knife Jugglers. In Spellsource, multiple classes have pre-buffs, and summoner has a lot.

I also think this gets in the way of pre-buffs having synergies with cards such as the soon to be gone Saronite Chain Gang, Hir'eek and Doppelgangster, as well as staying cards such as Ninja Aspirants, Corrupt Forerunner and Steelwing Rider, which depletes from the game.

If pre-buffs could be changed to increase the stats of the minion before it's summoned somehow, before battlecries, that would be ideal. So if I were to play a Wild Mutation into a Ninja Aspirants it'd start summoning the original ninja aspirants as a 5/5 and then the battlecry would trigger afterwards, summoning a copy of itself. I'm unsure on how doable this is, as I still don't perfectly know how it works, since the copy would likely start being summoned first.
If the way the ordering worked itself was changed I'd imagine there'd be certain significant ramifications and I'm uncertain of how doable that'd even be.

**Comment by wmarkowitz** [comment]
Resolved
