### ISSUE TITLE
Creating Cards

### ISSUE THREAD

**Issue by TarCreeper** [hiddenswitch/Spellsource-Server#11]
When I download the swagger-codegen 2.2.2 what means: "clone this repository"?

Thanks.

**Comment by doctorpangloss** [comment]
You can get a copy of the cards and code by cloning or downloading the repository. Cloning will tell your computer to keep track of all the changes you make, will let you download the latest code easily, and will let you share your updates here in a structured way.

<img width="451" alt="screenshot 2017-12-09 11 17 17" src="https://user-images.githubusercontent.com/2229300/33797258-b1434686-dcd2-11e7-869d-89dcd3ba65aa.png">

Click the Clone or Download button, and try Open in Desktop. You should be prompted to install the Github App. Though if that's a big hassle, just download the zip from that link in the picture instead!
