### ISSUE TITLE
Lich Basic Code Reworks and New Tokens

### ISSUE THREAD

**Issue by Samswize** [hiddenswitch/Spellsource-Server#1116]
Alright here be instructions

1. All current tokens for Lich should be replaced with these new ones. LichGhoul should be used for the Skills and Rise Again. anyways. LichSkeleton1 is used for Skull Missile, while LichSkeleton 2 is for Soldiers of the Wastes. And uh, LichMonstrosity is for Dark Ritual.
2. These "new" cards are replacing others. Rise Again is replacing Army of Undeath. Dark Ritual is replacing... ahem. Dark Ritual. Ice Beam is replacing Frost Blast.

[New folder.zip](https://github.com/hiddenswitch/Spellsource-Server/files/3220534/New.folder.zip)

**Comment by wmarkowitz** [comment]
according to #1199, we're scrapping Lich, so we're closing this.
