### ISSUE TITLE
Gurubashi Bloodletter and Berserk Spell Interaction

### ISSUE THREAD

**Issue by Logovazz** [hiddenswitch/Spellsource-Server#1119]
Intended Interaction: After Gurubashi Bloodletter hits something because of Berserk, it should stop attacking and remain as a 5/5.

Observed Interaction: Gurubashi Bloodletter hits a minion that it can survive a hit from and transforms, the Rage Behemoth token that comes out continues to hit the rest of the targets.

**Comment by wmarkowitz** [comment]
Was there another aspect to this? I tried doing these steps, but the observed interaction didn't occur.
