### ISSUE TITLE
The Hidden attribute given to a hero by Tanglefur says Stealth in a very small font

### ISSUE THREAD

**Issue by BattleDomeGuy** [hiddenswitch/Spellsource-Server#1121]
![image](https://user-images.githubusercontent.com/42615141/58495800-62652380-8146-11e9-8c59-6783797c2fee.png)

Should say Hidden and be bigger, or just have the smoke that Hidden minions have

**Comment by doctorpangloss** [comment]
fixed since 3.0.0
