### ISSUE TITLE
Immune Pirate still loses Dodge when attacking

### ISSUE THREAD

**Issue by BattleDomeGuy** [hiddenswitch/Spellsource-Server#1176]
the 1/1 Pirate that gains dodge when your opponent has no minions (forget the name), still loses dodge when it's given immune from the guard dude that gives adjacent Pirates immune

**Comment by wmarkowitz** [comment]
So I've found the two cards you mentioned (Hold Hunter and Gaudy Guard respectively), but I've been unable to recreate the bug you're mentioning here? Do you recall in more detail what happened to cause Hold Hunter to lose guard? (Play order, attacking, etc.)

**Comment by BattleDomeGuy** [comment]
I’m not gonna lie I was fresh from surgery when I sent that, on a bunch of medication. I don’t have a single clue about the order or attack or anything like that

**Comment by wmarkowitz** [comment]
No worries! I'm going to close this issue for now, but we'll be sure to keep an eye on it. If it comes back up, we'll reopen the issue and fix.
