### ISSUE TITLE
Deflect Procs Before Dodge. Should be the other way around.

### ISSUE THREAD

**Issue by InquisitorGrand** [hiddenswitch/Spellsource-Server#1192]
Spellsource Reproducible Issue Template

Reproduction steps:

 1. Summon Zen-noy-o-tron (or any other Deflect minion with Dodge)
 2. Do "lethal" damage to the minion (e.g., deal 2+ damage to the Zen-noy-o-tron
 3. Observe that the Deflect triggers before the Dodge trigger. The opposite should be the case.
 
Platform: [X] Windows, [X] Mac

**Comment by wmarkowitz** [comment]
These steps were done, but it was observed that Dodge triggered before Deflect. Was there perhaps an extraneous circumstance to this? In any case, we'll keep an eye on it and see if it comes up again.

**Comment by InquisitorGrand** [comment]
In the interaction I provided, I observed that the Zen-tron was hit for 3
damage by a vanilla token on the opponent's sides, then activated the
deflect before the dodge, dealing 3 damage to me while leaving the Dodge
intact. I then made an attack on my turn and attacked a minion, when the
dodge proc'd. I can try some more rigorous testing when I get the chance.

-Grand

**Comment by doctorpangloss** [comment]
Is there any follow up on this? Only **Wither** and dealing damage interact with "hitting shields," whose rule is, "Dodge processes before Deflect."
