### ISSUE TITLE
Quests should not appear in spell discovers

### ISSUE THREAD

**Issue by TarCreeper** [hiddenswitch/Spellsource-Server#12]
The Quests don't have to be discoverable.

**Comment by doctorpangloss** [comment]
Does this include Shadow Visions?

**Comment by TarCreeper** [comment]
From Shadow Visions, in Hearthstone, you can discover quests.

**Comment by doctorpangloss** [comment]
@TarCreeper I will address this issue. If you'd like to help with Kobolds and Catacombs you've been given Write access and should post to the Projects link whatever you're working on. I'm going in order alphabetically by class, then doing Neutrals last.
