### ISSUE TITLE
Fifi Fizzlewarp does not work in a deck with majority textless minions 

### ISSUE THREAD

**Issue by InquisitorGrand** [hiddenswitch/Spellsource-Server#1258]
Recently I tried out a Fifi Monk for a laugh, and noticed that despite every minion in my deck having no text/abilities, Fifi would not proc. This happens in a deck of entirely minions and one with textless minions with some spells. Bizarrely enough, I faced off against a Fifi Summoner in quick play and they were able to get their Fifi to proc,  so I'm not sure what the issue is.

**Comment by doctorpangloss** [comment]
please post the deck list here, because there's definitely a fifi test and it's pretty robust

**Comment by InquisitorGrand** [comment]
### Fifi Monk
# Class: JADE
# Format: Spellsource
#
# 2x (0) Rapier Rodent
# 2x (1) Hard Puncher
# 2x (1) Soothing Mists
# 2x (2) Black Ox Brew
# 2x (2) Chi Wave
# 1x (2) Fifi Fizzlewarp
# 1x (2) Mark of Despair
# 2x (2) Thuggish Fae
# 2x (4) Mutated Brute
# 2x (5) Chi Restoration
# 2x (5) Cybernetic Rager
# 2x (5) Fiery Tyrant
# 2x (6) Magma Hound
# 2x (8) Mechanical Monstrosity
# 2x (8) Phantom Advisor
# 2x (9) Blubber Behemoth

**Comment by doctorpangloss** [comment]
This was due to phanton advisor having a space in its name and therefore was fixed in #1466
