### ISSUE TITLE
Spellsource Client Freeze after obtaining minion from Unstable Portal

### ISSUE THREAD

**Issue by Boso101** [hiddenswitch/Spellsource-Server#13]
This Unstable Portal was obtained from a Primordial Glyph

**Comment by Boso101** [comment]
Would be important to note that this was off the built project and did not contain significant changes

**Comment by doctorpangloss** [comment]
Cool, I bet this is a problem with modifying costs

**Comment by doctorpangloss** [comment]
Note that if the client freezes, you can quit and restart, and it will reconnect you to your existing game.
