### ISSUE TITLE
Game stops immediately after opponent ends turn, leave the player stuck

### ISSUE THREAD

**Issue by InquisitorGrand** [hiddenswitch/Spellsource-Server#1302]
Every now and then after the opponent ends their turn, the game freezes on the intermediary period between the end of their turn and the start of the player's. You can click and drag cards around, but you will not be able to play them. You also do not draw a card, and the "YOUR TURN" message does not appear.

**Comment by doctorpangloss** [comment]
fixed since 3.0.0
