### ISSUE TITLE
Hex: Pig's pig doesn't restore health as intented

### ISSUE THREAD

**Issue by Bromora** [hiddenswitch/Spellsource-Server#1315]
it is as said, the pig is supposed to have an aftermath that restores 5 health to the "enemy champion" however it does not restore any health.

**Comment by wmarkowitz** [comment]
Was there another outside force at play? At the moment, it has been tested and seems to work as intended.

**Comment by Bromora** [comment]
after you saying that I tested again and it seems to have started working again, I am really confused as to why.
