### ISSUE TITLE
Blood Boil missing from Core Wraith

### ISSUE THREAD

**Issue by Bromora** [hiddenswitch/Spellsource-Server#1346]
![image](https://user-images.githubusercontent.com/18221278/63228429-c7cb2c80-c1ea-11e9-810f-060e697de633.png)

this spell is missing in the collection

**Comment by doctorpangloss** [comment]
(Fixed in 0.8.49+ because it had a repeated ID)
<img width="288" alt="Screenshot 2019-08-20 15 17 27" src="https://user-images.githubusercontent.com/2229300/63388534-9fb00a80-c35d-11e9-88be-149c9f571381.png">
