### ISSUE TITLE
"Crate of Dynamite" doesn't work as worded

### ISSUE THREAD

**Issue by Bromora** [hiddenswitch/Spellsource-Server#1356]
'give a minion "quickdraw; deal 1 damage to all enemy minions" however if put on the opponents minions, it will deal damage to their minions; also on YOUR turn.

Either it needs to be changed (also making it less flexible, but it is pretty strong anyway)
OR the wording should be "choose a minion, whenever you draw a card; deal 1 damage to all enemy minions" instead of using the keyword quickdraw; because that is incorrect

**Comment by doctorpangloss** [comment]
> it will deal damage to their minions; also on YOUR turn

I think that's the intent of the card. So I just need to know what the behaviour should be, and then I can change the text to be more clear. I believe the intent is

 1. Player casts Crate of Dynamite on opponent minion.
 2. Opponent draws card.
 3. Nothing happens.

 1. Player casts Crate of Dynamite on opponent minion.
 2. Player draws card.
 3. Deal 1 damage to all opposing minions.

 1. Player casts Crate of Dynamite on friendly minion.
 2. Opponent draws card.
 3. Nothing happens.

 1. Player casts Crate of Dynamite on friendly minion.
 2. Player draws card.
 3. Deal 1 damage to all opposing minions.

**Comment by Bromora** [comment]
"Choose a minion. Whenever you draw a card; deal 1 damage to all enemy minions" is the wording for this.
