### ISSUE TITLE
Otherworlder bug: Incandescent Mutation pings does not trigger Wither

### ISSUE THREAD

**Issue by AnterogradeNil** [hiddenswitch/Spellsource-Server#1364]
If a minion has the Wither keyword, it should proc Incandescent Mutation because it is the minion dealing the damage. It's kinda like a handbuff, not a persistent effect.

Bioweaponize works correctly though. The pings trigger Wither.

**Comment by AnterogradeNil** [comment]
Scratch that, Bioweaponize doesn't trigger its own Wither. If put on a minion with Wither though, that Wither triggers. But not its own.

**Comment by doctorpangloss** [comment]
there's a bigger problem that triggers do not activate until after a battlecry is activated. Toxic and Lifedrain are special cased, and clearly wither needs to be too. I will defer that change but it will be done
