### ISSUE TITLE
Otherworlder Bug: Enemy minions attacking Wither minions have the Wither debuff removed at the end of the same turn.

### ISSUE THREAD

**Issue by AnterogradeNil** [hiddenswitch/Spellsource-Server#1365]
It should act like freeze, where it carries over to their next turn. IIRC Frozen units stay frozen until they pass their turn without attacking when they normally could if they didn't have Freezing. Meaning, if an enemy attacks a Water Elemental, it freezes, then when their turn starts again it doesn't thaw out until they end their second turn.

Wither should be like that, where it lasts until the next time the victim makes (or passes) an attack. It should still deactivate at the end of the turn though, just to clarify.

**Comment by AnterogradeNil** [comment]
The official description of the keyword could be "Any minion damaged by this has -x attack until the end of their next turn."

**Comment by doctorpangloss** [comment]
now behaves like Freeze, fixed in #1366
