### ISSUE TITLE
Otherworlder Visual bug: Please make the OW color a bit darker. Buffed minion stats are almost invisible in front of the neon green background.

### ISSUE THREAD

**Issue by AnterogradeNil** [hiddenswitch/Spellsource-Server#1367]
Unless, of course, if you're already planning some UI changes that would fix this (like maybe black outlines around the numbers and letters or some overall graphical overhaul), then never mind this one.

**Comment by doctorpangloss** [comment]
<img width="640" alt="Screenshot 2019-09-01 18 00 55" src="https://user-images.githubusercontent.com/2229300/64083267-7f2f6b00-cce2-11e9-9404-32286a3db0ad.png">

Legibility has been improved, showing a darkened rectangle when a buff is applied. Buffs will be visualized differently in the new client.
