### ISSUE TITLE
In an AI match, the player should be able to choose the opponent's deck

### ISSUE THREAD

**Issue by BettyJJ** [hiddenswitch/Spellsource-Server#14]
In metastone we have this ability.
The opponent deck can be played either by a bot or by myself.
Thanks for making this cool project. Sorry if I asked a dumb question. :)

**Comment by doctorpangloss** [comment]
Yes, this is a feature that can be implemented.

I'm going to put together the planning board soon and I'll be sure to include it.

There's a way to do this now, but it's a little clunky and involves compiling the server.

**Comment by doctorpangloss** [comment]
@BettyJJ sorry this took so long, it's in the live build now.

**Comment by BettyJJ** [comment]
@doctorpangloss No need for sorry at all. Thank you so much for all this hard work!
