### ISSUE TITLE
Rules of Nature (Exile) does not show a targeting reticle when it could be cast and cannot be cast from hand.

### ISSUE THREAD

**Issue by InquisitorGrand** [hiddenswitch/Spellsource-Server#1428]
Ok this one is a little weird. So I tried to play Rules of Nature on my minion after my minion attacked and killed another friendly minion, just to see if the card worked. When I dragged it away from my hand and clicked, the card snapped back into my hand and glitched out. when I right clicked the card returned to my hand as normal, but presently, the card cannot be played from hand.
![2019-10-26](https://user-images.githubusercontent.com/50887931/67627150-a7d46c80-f81c-11e9-955b-b6a57ac9ee4d.png)

**Comment by doombubbles** [comment]
Old client
