### ISSUE TITLE
Obsigon (Exile) does not track and activate its opener properly 

### ISSUE THREAD

**Issue by InquisitorGrand** [hiddenswitch/Spellsource-Server#1440]
The design intent of this and many Exile cards was to track the enemies that attacked during their turn before yours. Obsigon does not track that, still showing "repeat 0 times" even after 2 enemy minions attacked the turn before.

**Comment by doombubbles** [comment]
Things seem to be fine as far as the server is concerned with this one? Maybe a client issue @doctorpangloss ?

**Comment by doombubbles** [comment]
Old Client
