### ISSUE TITLE
Terrified Tanuki nerf

### ISSUE THREAD

**Issue by BattleDomeGuy** [hiddenswitch/Spellsource-Server#1454]
This has been an issue for too long, and I apologize for being bad at balance

It needs to go from this

2 Lun 1 / 4 Beast
Hidden. After this attacks gain +1 Attack

to this

2 Lun 1 / 3 Beast
Hidden. After this attacks gain +1 Attack

This will help make it a lot less snowbally. Also when the hidden changes go live, that will help nerf this card

**Comment by doctorpangloss** [comment]
> Also when the hidden changes go live

What does that mean?
