### ISSUE TITLE
All for One should say "...for each friendly minion" and not "...for every other friendly minion" to make it consistent with its effect

### ISSUE THREAD

**Issue by BlobSlime** [hiddenswitch/Spellsource-Server#1484]
Porcival says this

**Comment by doombubbles** [comment]
Bit confused on this one. The current implementation of All for One does have it give attack specifically based on the number of other friendly minions, not all friendly minions. Is this just about the difference between the word "each" and the word "every"?

**Comment by BlobSlime** [comment]
When I played it in game, it didn’t seem that way, so I’m not sure where the problem lies anymore.

**Comment by Pircival** [comment]
All for One's description should be "Give a minion +1 Attack for each friendly minion."
