### ISSUE TITLE
Frost Lich Jaina should summon a Water Element immediately

### ISSUE THREAD

**Issue by BettyJJ** [hiddenswitch/Spellsource-Server#153]
Using the card Frost Lich Jaina should summon a Water Element immediately, but now this Water Element is not summoned. (By the way, other effects of the card is functioning alright, for instance killing a minion with hero power can correctly summon a Water Element.)

**Comment by doctorpangloss** [comment]
Thanks for the report, I hope to get to your oldest request (re: choose AI opponent) soon.

Please join us in our discord at https://discord.gg/t5ctkUT to check out the community cards, suggestions, etc. Thanks for playing!

**Comment by BettyJJ** [comment]
Thank you. 
I've never used discord before. Will give it a try.
