### ISSUE TITLE
Allow importing decks using the short code

### ISSUE THREAD

**Issue by BettyJJ** [hiddenswitch/Spellsource-Server#178]
By short code I mean something like:

AAEBAZ8FBu0FhRDWEYquAp29Ao7TAgyKAfsB9AXWBvYH3QqCEOIRibQC48sC7dIC+NICAA==

Now one can only import decks using the full code. If you copy the short code, it says you need the name of 30 cards, hero class and deck name. However, many HS sites only provide the short code now. Can you make it work? Thank you very much.

**Comment by doctorpangloss** [comment]
Yes, this can be added. There are a decent number of bugs to deal with, so your patience is greatly appreciated.

**Comment by doctorpangloss** [comment]
@BettyJJ this works now on public servers. The deck you posted in the issue looks like it worked well.

Please note that while the current name of the deck is "Netdeck" and you cannot edit the decks, the UI  outside of the battlefield is getting remade at the moment and it will support renaming decks in that interface.
