### ISSUE TITLE
Cannot play more than one game at a time due to failure to kill old games

### ISSUE THREAD

**Issue by azgano** [hiddenswitch/Spellsource-Server#25]
Not sure if it applies if you win a game vs the AI, but if you lose, the board and hands from the previous game will show in the next, with all the weapons, minions and cards in hand being uninteractable. These cards also carry into the next game after that, along with any cards played in every other previous game, these cards also don't affect board size or hand size.

There was also a bug where I almost immediately lost the game (not on 0 life), this might be related to the first bug.

Also, at some point the AI doesn't end it's turn and the game doesn't allow conceding or closing it, with the AIs turn lasting infinitely and the match ending if you close the game.

**Comment by doctorpangloss** [comment]
This is being fixed due to an issue in the latest server release. Thanks for reporting!
