### ISSUE TITLE
Jasper Spellstone triggering on Armor Loss, Branching Paths not working, Jade Idol shuffling one

### ISSUE THREAD

**Issue by azgano** [hiddenswitch/Spellsource-Server#29]
Lesser Jasper Spellstone (and its upgrade) seem to upgrade on armor loss as well as armor gain.

Branching Paths does nothing

Jade Idol only shuffles one copy into your deck, I have a script which I think will fix this, though it might interact incorrectly with Yogg.

spell_jade_idol_2:
{
	"name": "Shuffle 3 Copies",
	"baseManaCost": 1,
	"type": "SPELL",
	"heroClass": "DRUID",
	"rarity": "RARE",
	"description": "Shuffle 3 copies of this into your deck.",
	"targetSelection": "NONE",
	"spell": {
		"class": "CastRepeatedlySpell",
		"howMany": 3,
		"spell": {
		         "class": "ShuffleToDeckSpell",
		         "target": "NONE",
		         "card": "spell_jade_idol"
                }
	},
	"collectible": false,
	"set": "MEAN_STREETS_OF_GADGETZAN",
	"fileFormatVersion": 1
}

spell_jade_idol_3:
{
	"name": "Summon Jade Golem and Add 3",
	"baseManaCost": 1,
	"type": "SPELL",
	"heroClass": "DRUID",
	"rarity": "RARE",
	"description": "Summon a Jade Golem. Shuffle 3 copies of this card into your deck.",
	"targetSelection": "NONE",
	"spell": {
		"class": "MetaSpell",
		"spells": [
			{
		                "class": "CastRepeatedlySpell",
		                "howMany": 3,
		                "spell": {
		                         "class": "ShuffleToDeckSpell",
		                         "target": "NONE",
		                         "card": "spell_jade_idol"
                                }
			},
			{
				"class": "CreateSummonSpell",
				"name": "Jade Golem",
				"attackBonus": {
					"class": "AttributeValueProvider",
					"target": "FRIENDLY_PLAYER",
					"attribute": "JADE_BUFF",
					"offset": 1
				},
				"hpBonus": {
					"class": "AttributeValueProvider",
					"target": "FRIENDLY_PLAYER",
					"attribute": "JADE_BUFF",
					"offset": 1
				},
				"mana": {
					"class": "AlgebraicValueProvider",
					"operation": "MAXIMUM",
					"value1": {
						"class": "AttributeValueProvider",
						"target": "FRIENDLY_PLAYER",
						"attribute": "JADE_BUFF",
						"offset": 1
					},
					"value2": 10
				},
				"spell": {
					"class": "ModifyAttributeSpell",
					"target": "FRIENDLY_PLAYER",
					"attribute": "JADE_BUFF",
					"value": 1
				}
			}
		]
	},
	"collectible": false,
	"set": "MEAN_STREETS_OF_GADGETZAN",
	"fileFormatVersion": 1
}

**Comment by doctorpangloss** [comment]
(Fixed Jade Idol in code, wait for closure to know when it's deployed)
