### ISSUE TITLE
Color of health should only be red when the minion is damaged, not below base health

### ISSUE THREAD

**Issue by XBagon** [hiddenswitch/Spellsource-Server#390]
Reproduction steps:

 1. Play a minion.
 2. Set its Health below its original value 
 3. The color of the Health number is red. It should be white, red indicates damage, but this minion cannot be healed.

This is not the only case, the color of health seems to be determined by the comparison of Orignal Max Health and Health, while Current Max Health and Health should be compared.

**Comment by doctorpangloss** [comment]
Fixed since 3.0.7
