### ISSUE TITLE
FR: Automated testing based on Hearthstone replays

### ISSUE THREAD

**Issue by rhofour** [hiddenswitch/Spellsource-Server#443]
There is some publicly available replay data at: http://www.hearthscry.com/CollectOBot

We could take that data and replay it in spellsource, checking to see if the games progress identically. If they don't match then they give us reproducible examples of bugs to be fixed.

**Comment by rhofour** [comment]
Ah, I figured I was probably missing something. Instead we may be able check if a replay is feasible or not, but I imagine that's a lot harder than simply re-running it.

**Comment by doctorpangloss** [comment]
This is not realistic anymore
