### ISSUE TITLE
Local servers bot usage

### ISSUE THREAD

**Issue by webadict** [hiddenswitch/Spellsource-Server#508]
Are bots available to be used locally? Whenever I try to create a quick play game locally, I can't seem to correctly connect. As far as I can tell, it's able to find a bot account inside the database, but it doesn't appear to start the match, dying because it seems to fail somewhere after the creation of the game session. 

As far as I can tell, I get an error on bothClientsReady, since the bot never readies because it doesn't seem to start. My guess is that I need a separate process to run the bots, but I can't find one for it anywhere.

A second issue that happens because of this is that the missing player is never added to the GameContext (or possibly never given an ID, I didn't investigate further), causing errors for the player that's supposed to simply auto-win, since it can't remove an invalid player ID's board. These leaves the player with a screen showing "Connecting..." and that's it.

Reproduction steps:

 1. Followed all installation steps
 2. Ran a quick game on a local server
 3. Expecting a game, but instead the server is unable to start the game session. Client stuck on white screen trying to connect.
 
Platform: Likely all

**Comment by doctorpangloss** [comment]
Try the latest client from the launcher. Sorry about that, connecting locally from that client was not working for the last few days because I neglected to push an update.
