### ISSUE TITLE
Add a sandbox interface to gain mana, destroy/silence/copy a target, summon and draw

### ISSUE THREAD

**Issue by webadict** [hiddenswitch/Spellsource-Server#509]
Something that's entirely missing for this project is a debug mode. It makes testing and debugging harder, and if the goal is to mimic Hearthstone 100% correctly, having a way to test out cards in a modifiable environment would be nice.

This was a feature of MetaStone, and its removal really diverges it from this project entirely. Perhaps it does exist, and I'm missing it? But, I'm searching the code, and I'm not finding a way to enter such a mode.

I'm honestly here testing this project because I was planning to point MetaStone towards this project, since MetaStone is essentially dead. This project has a number of new features, but without a mode like that, this project fails to adhere to the same goals that MetaStone set out for, that being to create a place to simulate the rules of Hearthstone and to test the crazy combinations that could occur within an environment that didn't exist in Hearthstone itself or was incredibly hard to do.

I like a lot of the new features. But, honestly, this feels like trying to make a new Hearthstone with custom cards, instead of a place to simulate the things we can't in Hearthstone.

**Comment by doctorpangloss** [comment]
Go ahead and specify some concrete additional widgets and during the next big client update it'll get on the schedule.

Would you be interested in the following?

 - Destroy a character
 - Silence a character
 - Restore all health to the target
 - Draw a card
 - Gain 10 mana

Currently, there are a variety of test cards like `Cheat Cost Zero` that will automatically make all cards cost zero, for example. Sandbox features like free cards are supported by cards like this. It's definitely easier to think of the sandbox actions as cards that do something at the beginning of the game, let you discover things, etc. than authoring new UI.

**Comment by doctorpangloss** [comment]
wontfix
