### ISSUE TITLE
Floop doesn't change it's Health to 4 while in hand (but he does do it on the board)

### ISSUE THREAD

**Issue by BattleDomeGuy** [hiddenswitch/Spellsource-Server#542]
![image](https://user-images.githubusercontent.com/42615141/44480576-8e7cd280-a611-11e8-99bc-7e8ca6237797.png)
![image](https://user-images.githubusercontent.com/42615141/44480586-95a3e080-a611-11e8-9d5a-0ff3b56b4ba8.png)

**Comment by doctorpangloss** [comment]
this card isn't in the spellsource set anymore, but i believe the issue is fixed
