### ISSUE TITLE
Rafaam, Archivist just straight up doesn't work

### ISSUE THREAD

**Issue by BattleDomeGuy** [hiddenswitch/Spellsource-Server#543]
![image](https://user-images.githubusercontent.com/42615141/44480628-b9672680-a611-11e8-9c06-94fd523b5549.png)

This is a perfectly valid deck, but it doesn't trigger the Battlecry

**Comment by doctorpangloss** [comment]
Please provide some reproduction details because it seems to be working for me.

**Comment by doctorpangloss** [comment]
Could not reproduce this
