### ISSUE TITLE
Dragoon's Revitalize, Heavy Duty Dragoon, Menacing Dragotron and Ride the Nuke should have different stats

### ISSUE THREAD

**Issue by Beatdoof** [hiddenswitch/Spellsource-Server#557]
1. Revitalize costs 3 Mana instead of 1
2. Heavy Duty Dragoon is now a 4 Mana 3/6 instead of 4 Mana 3/5.
3. Menacing Dragotron is now a 5 mana 3/4 instead of 5 Mana 2/5.
4. Ride The Nuke now deals 9 damage instead of 7.

**Comment by doctorpangloss** [comment]
Is this addressed?
