### ISSUE TITLE
Searching the collection with numbers that are interpreted as mana costs causes surprising results

### ISSUE THREAD

**Issue by BattleDomeGuy** [hiddenswitch/Spellsource-Server#576]
![image](https://user-images.githubusercontent.com/42615141/44693454-2a557680-aa36-11e8-8c92-f9069aa9271f.png)

 
![image](https://user-images.githubusercontent.com/42615141/44693478-51ac4380-aa36-11e8-88da-ae999d127524.png)

**Comment by doctorpangloss** [comment]
The number is being interpreted as a mana cost
