### ISSUE TITLE
Can you provide a link to download the actual client?

### ISSUE THREAD

**Issue by BettyJJ** [hiddenswitch/Spellsource-Server#587]
Now one has to download the launcher and the launcher will download the latest build of the client. This is nice if you have a good Internet connection. However, in some places the Internet connection is not so good (for instance, in mainland China we have GFW, which severely worsens our Internet connection). The launcher often fails to download the client for me. If there is a separate download link, I could try to download it with some other tool which has a better chance of success. Hope you can understand this request. Thank you very much!

**Comment by doctorpangloss** [comment]
Totally. I’ll provide direct links soon.

**Comment by doctorpangloss** [comment]
you can now access the build online at playspellsource.com
