### ISSUE TITLE
Quest check / completion should trigger after a minion's Battlecry, not before it.

### ISSUE THREAD

**Issue by BattleDomeGuy** [hiddenswitch/Spellsource-Server#595]
Eternal Knight shouldn't be able to transform Crystal Core into an Eternal Knight, Novice Engineer shouldn't be able to add Crystal Core to your hand when you have 9 cards in hand

**Comment by doctorpangloss** [comment]
wontfix, although 4412d5a fixes the crystal core issue, although that card is retired
