### ISSUE TITLE
[Cards] - Grobbulus, Mutating Injection, and Poison Cloud

### ISSUE THREAD

**Issue by Boso101** [hiddenswitch/Spellsource-Server#652]
https://www.dropbox.com/s/nkhgx2xiuc8bm5w/Grobbulus.rar?dl=0

**Comment by doctorpangloss** [comment]
Thanks for this, I'm going to look at it soon!

**Comment by doctorpangloss** [comment]
Could you maybe do this as a pull request so I can see the test results?

**Comment by Boso101** [comment]
Of course
