### ISSUE TITLE
Reno Jackson "your deck has no duplicate" battlecry does not work

### ISSUE THREAD

**Issue by staticoblivion** [hiddenswitch/Spellsource-Server#739]
Spellsource Reproducible Issue Template

Reproduction steps:

 1. Perform action 1
 2. Perform action 2
 3. Observe X. The user expects Y.
 
Platform: [ ] Windows, [ ] Mac

Design or Graphics Glitches: Please attach a screenshot.

**Comment by staticoblivion** [comment]
It does not work. It should heal my hero to full health because I have a deck full of legendaries with no duplicate.

**Comment by doctorpangloss** [comment]
Can you post your deck list by visiting the Collection view, selecting your deck from the right, then clicking the Share icon (it looks like a > character), then pasting the deck list into a comment here? Thank you.

**Comment by doctorpangloss** [comment]
I think Prince Malchezaar shuffled duplicates, and it doesn't anymore. When release notes appear in the game indicating that this fix has been made, the public servers have been updated (they aren't at the moment). Thank you for reporting this issue!
