### ISSUE TITLE
runsims.sh missing

### ISSUE THREAD

**Issue by djdookie** [hiddenswitch/Spellsource-Server#762]
The file https://github.com/hiddenswitch/Spellsource-Server/blob/master/cluster/runsims.sh
described in 
https://github.com/hiddenswitch/Spellsource-Server/tree/master/cluster
is not existing.

And I believe `python3 -m spellsource.ext.datasources` does nothing. I get no output at all.

**Comment by doctorpangloss** [comment]
Sorry about that. `runsims.sh` has been deprecated. I've restored the file. I also address the issue with HS Replay data.

**Comment by djdookie** [comment]
Thanks @doctorpangloss !
