### ISSUE TITLE
Summoner GvG, TGT and some WoTOG changes

### ISSUE THREAD

**Issue by TheFlawlessWalrus** [hiddenswitch/Spellsource-Server#797]
[GvG+TGT List + WoTOG changes.zip](https://github.com/hiddenswitch/Spellsource-Server/files/2695042/GvG%2BTGT.List.%2B.WoTOG.changes.zip)

Some of them might not be that functional, just a heads up

**Comment by doctorpangloss** [comment]
0.8.4
