### ISSUE TITLE
Playing roll on a minion summons the correct stats when buffed, but does not show those stats in hand

### ISSUE THREAD

**Issue by LyokoBarbossa** [hiddenswitch/Spellsource-Server#801]
Reproduction steps:

 1. Play a minion with a buff to stats.
 2. Play Roll on said minion.
 3. Buffs vanish from minion. Roll should allow buffs to remain.
 
Platform: [ X ] Windows, [ ] Mac

**Comment by doctorpangloss** [comment]
This is part of a longstanding bug where cards in the hand do not correctly show their buffed states in the client.
x
