### ISSUE TITLE
Dragoon RR, and some missing additions and balance changes as well

### ISSUE THREAD

**Issue by Beatdoof** [hiddenswitch/Spellsource-Server#802]
Rastakhan's Rumble set: https://imgur.com/a/aku35QU

Missing stuff:
Consume Mind should be replaced with this now https://i.imgur.com/Mq0PSaE.png
Both Cult Reverend and Runt Leader is still not added yet
Fissure should be renamed Gobble now
Hornmender should be replaced with this now https://hearthcards.ams3.digitaloceanspaces.com/95/da/ac/80/95daac80.png
Pyroblaster Zagrosz should be a Dragon
Exotic Menace should be a Beast
Manufacturing should be an Epic
Twilight Redbane should be a Dragon
Explosive Rune! should be renamed to Explosive Ride!
Flamewarper should be a Mech
Lady Deathwhisper should be renamed to Sapphiron and is a Dragon as well
Anemic Cannon should be renamed to Hemocannon

Balance changes:
Mountain Whelp is now a 2/3 with Charge
Glacial Wyvern is now a 7 mana 5/9
Manufacturing should now read "Summon a copy of a friendly minion. If it's a Mech, summon two copies instead."
Marrow Cleaver is now a 4 mana 5/1 weapon
Lesser Garnet Spellstone and Garnet Spellstone now only needed 6 Attack to trigger its upgrade
Tol'vir Vitalizer is now a 5/6
Headhunter is now a 5/9
The Dreadtalon is now a 5/2

**Comment by doctorpangloss** [comment]
0.8.4
