### ISSUE TITLE
Where is the unity project for the client located?

### ISSUE THREAD

**Issue by Boso101** [hiddenswitch/Spellsource-Server#9]
Atm for myself I wish to add some hearthstone textures and icons, where are the unity files located? Btw successfully implemented "Gather your Party" and it works fine.

**Comment by doctorpangloss** [comment]
I have to remove the Unity asset store plugins that I use, which is going to take at least a week. In the meantime, I've invited you to the private repo.

**Comment by Demitor** [comment]
Will the Unity project be released publicly?
I am asking because i would like to add some assets myself.

**Comment by doctorpangloss** [comment]
@Demitor please join us on the Discord to discuss

https://discord.gg/DFrFNWA
