### ISSUE TITLE
Swapped Stats issue

### ISSUE THREAD

**Issue by LyokoBarbossa** [hiddenswitch/Spellsource-Server#915]
Reproduction steps:

 1. Play any damaged minion and G'huun (also damaged).
 2. Play any spell or minion that swaps their stats.
 3. Watch G'huun's effect double. The minions' swapped stats count as their new max health -- therefore no longer damaged and should not be capable of benefiting from G'huun's effect.
 
Platform: [ X ] Windows, [ ] Mac

![image](https://user-images.githubusercontent.com/16317609/51165154-e5a36e00-1864-11e9-9cc5-ab53d0051d3a.png)

**Comment by LyokoBarbossa** [comment]
Just a quick note, this means that 0/3 Red Crane Statue (i used Defile on both of them) should be an 11/10, not... whatever the hell is going on there. XD

**Comment by doctorpangloss** [comment]
What are the rules for swapping health on health buffed minions? I don't know.

**Comment by LyokoBarbossa** [comment]
> 
> 
> What are the rules for swapping health on health buffed minions? I don't know.

The main rule of thumb is that the minion's current stats upon swapping transfer over and become permanent; however, once this happens, the minion is no longer considered "damaged".
