### ISSUE TITLE
Witch Doctor Card Update

### ISSUE THREAD

**Issue by Logovazz** [hiddenswitch/Spellsource-Server#937]
New batch of Witch Doctor cards.
Some updates include:
- Bladesworn is now a 3 mana 4/2 that gains +1 Health whenever you cast a spell on it.
- Ritual Dagger is now a Battlecry: Add a random Voodoo spell to your hand.
- Split Personality can now only target friendly minions.
- Fading Berserker has fixed text description.
And a bunch of new cards.
[Witch Doctor - v2.0 Cards.zip](https://github.com/hiddenswitch/Spellsource-Server/files/2790012/Witch.Doctor.-.v2.0.Cards.zip)

**Comment by doctorpangloss** [comment]
Addressed by f176d03
